version: '2'
services:
  php:
    image: dovel-php:7.2
    container_name: dovel_php
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - '../project:/usr/local/src:delegated'
    networks:
      - dovel_network

  nginx:
    image: dovel-nginx:1.5
    container_name: dovel_nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '../project:/usr/local/src:delegated'
    networks:
      - dovel_network

  mysql:
    image: mysql:8.0.12
    container_name: dovel_mysql
    ports:
      - '3308:3306'
    env_file:
      - .env
    networks:
      - dovel_network

  redis:
    image: redis:5.0.0
    container_name: dovel_redis
    ports:
      - '6379:6379'
    volumes:
      - 'redis-data:/data'
    networks:
      - dovel_network

volumes:
  redis-data:

networks:
  dovel_network:
    driver: bridge